# Generated by Django 5.0.6 on 2024-05-26 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='status',
            field=models.CharField(choices=[('P', 'PENDENTE'), ('E', 'ENTREGUE'), ('C', 'CANCELADO')], default='P', max_length=1),
        ),
    ]
