# Generated by Django 5.0.6 on 2024-05-26 00:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0003_pedido_datainclusao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='dataInclusao',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Inclusão'),
        ),
    ]
