# Generated by Django 5.0.6 on 2024-05-26 00:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0004_alter_pedido_datainclusao'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='dataInclusao',
            new_name='data_inclusao',
        ),
    ]
