# Generated by Django 5.0.6 on 2024-05-27 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos', '0005_rename_datainclusao_pedido_data_inclusao'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='distancia',
            field=models.DecimalField(decimal_places=2, default=5, max_digits=10),
            preserve_default=False,
        ),
    ]
